name: TheMortalRanks
main: HTTPS7Team\TheMortalRanks\Main	
version: 1.1.3
api:
 - 3.0.0-ALPHA5
 - 3.0.0-ALPHA6
 - 3.0.0-ALPHA7
 - 3.0.0-ALPHA8
 - 3.0.0-ALPHA9
 - 3.0.0-ALPHA10
 - 3.0.0-ALPHA11
load: POSTWORLD
author: HTTPS7Team
commands:
  member:
   description: This will update you to a special unregistered rank-up group!
   usage: "/member"
   permission: member.command
  donater:
   description: This will update you to a special unregistered rank-up group!
   usage: "/donater"
   permission: donater.command
  youtuber:
   description: This will update you to a special unregistered rank-up group!
   usage: "/youtuber"
   permission: youtuber.command
  staffop:
   description: This will take away your unregistered rank-up group!
   usage: "/staffop"
   permission: staff.command
  permissions:
   svipupdate:
     default: false
   sviplusupdate:
     default: false
   mvpupdate:
     default: false
   resetsgroups:
     default: false
  children:
     svip.update:
        default: op
        description: "Gives you perms to run the command"
     sviplus.update:
       default: op
       description: "Gives you perms to run the command"
     mvp.update:
       default: op
       description: "Gives you perms to run the command"
     groups.reset:
       default: op
       description: "Gives you perms to run the command"
