name: TheMortalRanks
main: HTTPS7Team\TheMortalRanks\Main	
version: 1.1.3
api:
 - 3.0.0-ALPHA5
 - 3.0.0-ALPHA6
 - 3.0.0-ALPHA7
 - 3.0.0-ALPHA8
 - 3.0.0-ALPHA9
 - 3.0.0-ALPHA10
 - 3.0.0-ALPHA11
load: POSTWORLD
author: HTTPS7Team
commands:
  member:
   description: "§bThis command is only for Member and up!"
   usage: "/member"
   permission: member.command
  donater:
   description: "§bThis command is only for Donaters!"
   usage: "/donater"
   permission: donater.command
  youtuber:
   description: "§bThis command is only for Youtubers and up!"
   usage: "/youtuber"
   permission: youtuber.command
  staffop:
   description: "§bThis command is only for Staff!"
   usage: "/staff"
   permission: staffop.command
  permissions:
   member.command:
     default: false
   donater.command:
     default: false
   youtuber.command:
     default: false
   staffop.command:
     default: false
  children:
     svip.update:
        default: op
        description: "Gives you perms to run the command"
     sviplus.update:
       default: op
       description: "Gives you perms to run the command"
     mvp.update:
       default: op
       description: "Gives you perms to run the command"
     groups.reset:
       default: op
       description: "Gives you perms to run the command"
